language: bash
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - shellcheck
branches:
  only:
    - master
install:
  - ./install.sh
script:
  - ./build.sh
  - ./tests/test-custom-check.sh
notifications:
  email: false
